version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
    container_name: fastapi_backend
    command: ${FASTAPI_COMMAND}
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis

  worker:
    build:
      context: .
    container_name: celery_worker
    command: ${CELERY_WORKER_COMMAND}
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - rabbitmq
      - redis
    restart: always

  flower:
    image: mher/flower
    container_name: flower_monitor
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - rabbitmq
      - redis
